default: &default
  adapter:  postgresql
  encoding: unicode
  url:      <%= ENV.fetch('DATABASE_URL') %>

development: *default

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_TEST_URL') %>

production:  *default
